name: Check
on:
  pull_request:
  push:
jobs:
  check:
    name: Flake
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Git repository'
        uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@v8
      - name: 'Flake Check'
        run: |
          nix flake check -L

  tests-check:
    name: 'Test Flake'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
      - name: 'Set up Git repository'
        uses: actions/checkout@v4
      - name: 'Install Nix'
        uses: DeterminateSystems/nix-installer-action@v8
      - name: 'Flake Check'
        run: |
          nix flake check -L
